version: '3.9'
services: 
  server:
    build: .
    ports:
      - "3000:3000"
  db:
    image: 'postgres'
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 6528
      POSTGRES_DB: postgres
    ports:
      - "4321:5432"
    volumes:
      - data:/var/lib/postgresql/data
volumes:
  data:      
