version: '3.9'
services: 
  server:
    build: .
    ports:
      - "3000:3000"
  db:
    image: 'postgres'
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 6528
      POSTGRES_DB: postgres
    ports:
      - "4321:5432"
    volumes:
      - data:/var/lib/postgresql/data
volumes:
  data:      

  # adminer: 
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080
#   api:
#     container_name: users-api
#     build:
#       context: ./
#       target: production
#     image: users-api
#     depends_on:
#       - db
#     ports:
#       - 3000:3000
#     environment:
#       NODE_ENV: production
#       DB_HOST: db
#       DB_PORT: 5432
#       DB_USER: postgres
#       DB_PASSWORD: 6528
#       DB_NAME: postgres
#     links:
#       - db
#     volumes:
#       - './:/src'
# volumes:
#   db:
#     driver: local